BACKEND_BUCKET = "infra-bucket-project"

STACK_FOLDER = "CUSTOMER_DOGECOIN"
STACK_PROJECT = "DOGECOIN_DEV"
STACK_BILLING_ACCOUNT = ""

STACK_ENVIRONMENT = "DEV"
STACK_ENVIRONMENT_NAME = "DEV_ENVIRONMENT"
STACK_ENVIRONMENT_TYPE = "DEV_TYPE"

STACK_URL = "dogecoin.beta.gcpcloud.com"

STACK_NAME = 

CUSTOMER = 

STACK_REGION = ""
